In [1]:
!pip install jcopml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
!pip install keras==2.3.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
!pip install tensorflow==2.0.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
# Import all libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
df = pd.read_excel('/content/drive/MyDrive/Client/blabla/Final_Putusan_Perceraian.xlsx')
df.head()

No Jenis  UP  UT  UK  JA Mediasi  Alasan     Putusan
0   1    CG  40  48   9   1   Gagal      26  Dikabulkan
1   2    CG  44  49  20   5   Gagal     147  Dikabulkan
2   3    CG  31  33   7   2   Gagal     478  Dikabulkan
3   4    CG  48  42  20   2   Gagal      26  Dikabulkan
4   5    CG  28  29   4   1   Gagal     234  Dikabulkan

In [7]:
df = df.drop(['No', 'Mediasi'], axis=1)
df.head()

Jenis  UP  UT  UK  JA  Alasan     Putusan
0    CG  40  48   9   1      26  Dikabulkan
1    CG  44  49  20   5     147  Dikabulkan
2    CG  31  33   7   2     478  Dikabulkan
3    CG  48  42  20   2      26  Dikabulkan
4    CG  28  29   4   1     234  Dikabulkan

In [8]:
df.Putusan.value_counts()

Dikabulkan    724
Ditolak        55
Name: Putusan, dtype: int64

In [9]:
Dikabulkan= df[df.Putusan == 'Dikabulkan'][:100]
Ditolak= df[df.Putusan == 'Ditolak']
df = pd.concat([Dikabulkan,Ditolak])

In [10]:
#Transormasi Data menggunakan LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df['Putusan']= le.fit_transform(df['Putusan'].values)
df['Jenis']= le.fit_transform(df['Jenis'].values)

In [12]:
df

Jenis  UP  UT  UK  JA  Alasan  Putusan
0        0  40  48   9   1      26        0
1        0  44  49  20   5     147        0
2        0  31  33   7   2     478        0
3        0  48  42  20   2      26        0
4        0  28  29   4   1     234        0
..     ...  ..  ..  ..  ..     ...      ...
608      0  39  45  20   7       7        1
618      0  46  50  26   8       5        1
646      1  32  42   2   0       7        1
694      0  39  60   9   1       6        1
733      0  56  71  33   7       6        1

[155 rows x 7 columns]

In [13]:
df.Putusan.value_counts()

0    100
1     55
Name: Putusan, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
X = df.drop(columns='Putusan').values
y = df['Putusan'].values


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((124, 6), (31, 6), (124,), (31,))

##Import minmaxscaler

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
scaler = MinMaxScaler()

In [18]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [19]:

import tensorflow as tf


model = tf.keras.models.Sequential() #arsitektur

model.add(tf.keras.layers.Dense(6,input_shape=[6] ))
model.add(tf.keras.layers.Dense(9, activation = 'relu'))
model.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

model.compile(loss='mean_squared_error', optimizer=tf.keras.optimizers.Adam(0.09), metrics=['accuracy'])


In [20]:
weight=model.get_weights()
weight

[array([[-0.49199396,  0.66960937,  0.44008285,  0.09518683, -0.01626599,
          0.58462566],
        [ 0.0649237 , -0.18784595,  0.55888325, -0.51178056, -0.25461483,
         -0.25244763],
        [-0.18206513,  0.60506517,  0.17249256, -0.30961564,  0.04249126,
         -0.17273903],
        [-0.02166581, -0.6460761 ,  0.49883324,  0.4240281 , -0.2009651 ,
          0.12019271],
        [-0.68516177, -0.13010597, -0.5920263 ,  0.54949826, -0.21807048,
          0.33910054],
        [ 0.37074155,  0.30639237,  0.4605909 ,  0.00659549,  0.60098904,
          0.18236691]], dtype=float32),
 array([0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.04961264,  0.13876462,  0.35223126, -0.03321058,  0.54892796,
          0.47884363, -0.3223759 ,  0.39477736, -0.52169126],
        [-0.05812663, -0.10345978, -0.10653436,  0.48220593, -0.26651558,
          0.57840556, -0.34415165,  0.57925993,  0.62785417],
        [-0.30900738,  0.38653928, -0.4989782 , -0.5607788 ,  0.5557806 ,
      

In [21]:
model.fit(X_train,y_train, epochs=300, batch_size=128)

Train on 124 samples
Epoch 1/300
124/124 [==============================] - 1s 5ms/sample - loss: 0.2511 - accuracy: 0.6532
Epoch 2/300
124/124 [==============================] - 0s 65us/sample - loss: 0.2363 - accuracy: 0.6452
Epoch 3/300
124/124 [==============================] - 0s 36us/sample - loss: 0.2295 - accuracy: 0.6452
Epoch 4/300
124/124 [==============================] - 0s 29us/sample - loss: 0.2219 - accuracy: 0.6452
Epoch 5/300
124/124 [==============================] - 0s 43us/sample - loss: 0.2192 - accuracy: 0.6935
Epoch 6/300
124/124 [==============================] - 0s 68us/sample - loss: 0.2127 - accuracy: 0.6935
Epoch 7/300
124/124 [==============================] - 0s 37us/sample - loss: 0.2084 - accuracy: 0.6935
Epoch 8/300
124/124 [==============================] - 0s 44us/sample - loss: 0.2039 - accuracy: 0.7016
Epoch 9/300
124/124 [==============================] - 0s 43us/sample - loss: 0.2029 - accuracy: 0.7016
Epoch 10/300
124/124 [======================

In [22]:
val_loss,val_acc = model.evaluate(X_test, y_test, batch_size=32)
print(val_loss,val_acc)

31/1 [==================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================] - 0s 4ms/sample - loss: 0.2493 - accuracy: 0.7419
0.2492929399

In [23]:
predict_test = model.predict(X_test).round()
print(predict_test)

[[1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]]


In [24]:
y_test

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0])

In [25]:
weight=model.get_weights()
weight

[array([[ 1.5874939e+00,  9.4156408e-01, -5.8356464e-01,  1.0052236e+00,
         -6.1962575e-01,  9.0621227e-01],
        [-4.8958120e-01,  1.0727813e+00,  2.7005632e+00, -1.0842978e+00,
         -1.0863290e+00, -3.0483520e-03],
        [ 1.3249234e+00,  1.3990954e+00,  7.0168829e-01, -1.1271496e+00,
         -3.9750639e-01,  2.1907918e-01],
        [ 1.1021933e-01, -5.4466963e-01,  3.7674341e-02,  4.2251360e-01,
          5.6065861e-02, -2.8902376e-01],
        [-9.0932101e-01, -2.0469546e-01,  1.0246987e+00, -1.3075004e+00,
         -8.0107874e-01,  2.7436650e-01],
        [-2.0446296e-01, -6.3149805e+00,  6.5710225e+00, -8.1460638e+00,
          1.2958585e+01, -1.2235940e+01]], dtype=float32),
 array([-0.89518017,  0.18029806, -0.581762  ,  0.67815596,  0.15499765,
        -0.20629174], dtype=float32),
 array([[ 1.09911   , -0.34224325,  0.37553346, -0.76173675,  0.66059226,
          1.8326921 , -0.2713924 ,  0.94688094, -0.0577217 ],
        [-2.6351516 ,  0.04947709, -1.0629443 

In [26]:
print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       0.88      0.70      0.78        20
           1       0.60      0.82      0.69        11

    accuracy                           0.74        31
   macro avg       0.74      0.76      0.74        31
weighted avg       0.78      0.74      0.75        31

